<?php

namespace Swourire\chatutils;

use pocketmine\event\Listener;
use pocketmine\plugin\PluginBase;
use pocketmine\Server;
use Swourire\chatutils\Commands\muteChatCommand;
use Swourire\chatutils\Commands\sayAllCommand;

class Loader extends PluginBase implements Listener
{
    public function onEnable()
    {
        Server::getInstance()->getCommandMap()->register("mc", new muteChatCommand($this));
        Server::getInstance()->getCommandMap()->register("sa", new sayAllCommand($this));
        $this->getServer()->getPluginManager()->registerEvents(new chatListener($this), $this);
        parent::onEnable(); // TODO: Change the autogenerated stub
    }
}